### ISSUE TITLE
V3 Code Issue

### ISSUE THREAD

**Issue by itskegnh** [Sequitur-Studios/Cell-Machine-Mystic-Mod#76] opened 2021-08-03 00:20 UTC
**Describe the bug**
When you first download the game, your code now defaults to V3, this is a good feature, but while it shows V3 as the chosen option, V1 is used when you export.

**To Reproduce**

1. Download Mystic Mod
2. Export a Level (exports as v1)
3. Go to Settings
3. Click on Export code
4. Change to V1 then back to V3
5. Fixed

**Expected behavior**
V3 code export when download.

**Debug info**

**Additional context / media**

**Comment by f1shy-dev** [comment] 2021-08-03 00:34
This is a duplicate of #64 and is fixed in the latest GUI PR.

**Closed** 2021-08-03 07:05 UTC
Labels: bug
